import cv2
import pandas as pd
import sys
from pathlib import Path


# ============================================================
# Project paths
# 项目路径
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"
RESULTS_DIR = BASE_DIR / "results"


def resolve_session_dir(path_text):
    """
    中文：
    把用户输入的 session 路径转成绝对路径。

    例如：
        data/raw/session_20260514_123722

    会变成：
        D:/gaze_palsy_project/data/raw/session_20260514_123722

    English:
    Convert a user-provided session path into an absolute path.
    """
    session_dir = Path(path_text)

    if not session_dir.is_absolute():
        session_dir = BASE_DIR / session_dir

    return session_dir


def find_eye_csv(session_dir):
    """
    中文：
    找到 02_extract_eye_landmarks.py 生成的 eye landmarks CSV。

    正常情况下，02 会输出到：
        data/processed/session_xxxx_eye_landmarks.csv

    但为了保险，这里也会检查 raw/session 文件夹。

    English:
    Find the eye landmark CSV generated by 02_extract_eye_landmarks.py.
    """

    session_name = session_dir.name

    possible_paths = [
        PROCESSED_DATA_DIR / f"{session_name}_eye_landmarks.csv",
        session_dir / f"{session_name}_eye_landmarks.csv",
        session_dir / "eye_landmarks.csv",
    ]

    for path in possible_paths:
        if path.exists():
            return path

    print("ERROR: Cannot find eye landmark CSV.")
    print("Tried these locations:")

    for path in possible_paths:
        print(f"  {path}")

    return None


def draw_red_dot(frame, x, y, label):
    """
    中文：
    在视频帧上画虹膜中心红点。

    x, y 是 02 算出来的虹膜中心像素坐标。

    English:
    Draw a red dot at the iris center on one video frame.
    """

    if pd.isna(x) or pd.isna(y):
        return frame

    x = int(round(x))
    y = int(round(y))

    # 中文：红色实心点，表示虹膜中心。
    # English: Red filled dot represents the iris center.
    cv2.circle(frame, (x, y), 2, (0, 0, 255), -1)

    # 中文：白色外圈，让红点在眼睛区域更明显。
    # English: White outline makes the red dot easier to see.
    cv2.circle(frame, (x, y), 4, (255, 255, 255), 1)

    # 中文：标记左眼或右眼。
    # English: Label left or right iris.
    cv2.putText(
        frame,
        label,
        (x + 8, y - 8),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.45,
        (0, 0, 255),
        1
    )

    return frame


def main():
    """
    中文：
    读取原始 webcam.mp4 和 02 生成的 eye_landmarks.csv，
    然后把左右虹膜中心画成红点，输出一个新视频。

    输入：
        data/raw/session_xxxx/webcam.mp4
        data/processed/session_xxxx_eye_landmarks.csv

    输出：
        results/session_xxxx_iris_overlay.mp4

    English:
    Read webcam.mp4 and eye_landmarks.csv,
    draw red dots on left/right iris centers,
    and save a new overlay video.
    """

    if len(sys.argv) < 2:
        print("Usage:")
        print("python scripts/05_iris_overlay_video.py data/raw/session_YYYYMMDD_HHMMSS")
        return

    session_dir = resolve_session_dir(sys.argv[1])
    session_name = session_dir.name

    video_path = session_dir / "webcam.mp4"
    eye_csv_path = find_eye_csv(session_dir)

    if not video_path.exists():
        print(f"ERROR: Cannot find video: {video_path}")
        return

    if eye_csv_path is None:
        return

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    output_video_path = RESULTS_DIR / f"{session_name}_iris_overlay.mp4"

    print("========== Input / Output ==========")
    print(f"Input video: {video_path}")
    print(f"Eye CSV: {eye_csv_path}")
    print(f"Output video: {output_video_path}")
    print("====================================")

    # 中文：读取 02 生成的眼睛坐标 CSV。
    # English: Read the eye coordinate CSV generated by 02.
    eye_df = pd.read_csv(eye_csv_path)

    required_columns = [
        "frame_id",
        "face_detected",
        "left_iris_x_px",
        "left_iris_y_px",
        "right_iris_x_px",
        "right_iris_y_px",
    ]

    for col in required_columns:
        if col not in eye_df.columns:
            print(f"ERROR: Missing column in eye CSV: {col}")
            return

    # 中文：
    # 用 frame_id 作为索引。
    # 这样视频读到第几帧，就可以直接找到 CSV 里对应的虹膜坐标。
    #
    # English:
    # Use frame_id as index so each video frame can directly match its iris coordinates.
    eye_df = eye_df.set_index("frame_id")

    # 中文：打开原始视频。
    # English: Open original webcam video.
    cap = cv2.VideoCapture(str(video_path))

    if not cap.isOpened():
        print("ERROR: Cannot open input video.")
        return

    fps = cap.get(cv2.CAP_PROP_FPS)

    if fps <= 0:
        fps = 30

    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    if width <= 0 or height <= 0:
        print("ERROR: Invalid video size.")
        cap.release()
        return

    # 中文：创建输出视频 writer。
    # English: Create output video writer.
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    out = cv2.VideoWriter(
        str(output_video_path),
        fourcc,
        fps,
        (width, height)
    )

    if not out.isOpened():
        print("ERROR: Cannot create output video.")
        cap.release()
        return

    frame_id = 0
    total_frames = 0
    drawn_frames = 0

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        total_frames += 1

        status = "no landmark row"
        status_color = (0, 0, 255)

        if frame_id in eye_df.index:
            row = eye_df.loc[frame_id]

            if row["face_detected"] == 1:
                frame = draw_red_dot(
                    frame,
                    row["left_iris_x_px"],
                    row["left_iris_y_px"],
                    "L"
                )

                frame = draw_red_dot(
                    frame,
                    row["right_iris_x_px"],
                    row["right_iris_y_px"],
                    "R"
                )

                drawn_frames += 1
                status = "iris dots drawn"
                status_color = (0, 255, 0)
            else:
                status = "face not detected"
                status_color = (0, 0, 255)

        # 中文：左上角显示当前帧编号。
        # English: Show current frame id.
        cv2.putText(
            frame,
            f"Frame: {frame_id}",
            (20, 30),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            (255, 255, 255),
            2
        )

        # 中文：显示当前检测状态。
        # English: Show current detection status.
        cv2.putText(
            frame,
            status,
            (20, 60),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            status_color,
            2
        )

        out.write(frame)
        frame_id += 1

    cap.release()
    out.release()

    print("Done.")
    print(f"Output video saved to: {output_video_path}")
    print(f"Total frames: {total_frames}")
    print(f"Frames with iris dots: {drawn_frames}")


if __name__ == "__main__":
    main()